DROP DATABASE IF EXISTS $DB WITH (FORCE);
DROP ROLE IF EXISTS $USERNAME;

CREATE DATABASE $DB
WITH OWNER adminuser;

 \connect $DB;

CREATE SCHEMA calendar;

CREATE ROLE $USERNAME
LOGIN
PASSWORD '$PASSWORD';

GRANT ALL ON SCHEMA calendar TO $USERNAME;

ALTER USER $USERNAME SET search_path = calendar;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA calendar;